### ISSUE TITLE
Remove Project Dates

### ISSUE THREAD

**Issue by DavidSchirduan** [hydecorp/hydejack#116]
I use the Projects more like a store-front, and sorting them by date is unhelpful, especially how they are broken up into "2018", "2017" sections. Is there an easy way to simply remove the date headers? 

I don't mind showing them by date, but breaking them up makes it seem like my old stuff is...well old. I want it all in one group.

**Comment by DavidSchirduan** [comment]
Feel free to ignore this suggestion; it's an easy enough change to make on my own; I just don't know if anyone else might be interested in it.

**Comment by qwtel** [comment]
I think I've seen others use it that way as well. Not sure if I should just go with a blank "no_groups" option, or come up with something more generic that allows arbitrary groups/headlines.

**Comment by inspectordanno** [comment]
Hey qwtel,

Sorry to bump this post, but is there any way you could implement something like this (sorting by group, rather than year) in the next major release? I think it would really make a killer projects layout!!

**Comment by qwtel** [comment]
FYI: I have some work in progress that adds an option to disable grouping: https://qwtel.com/projects/

**Comment by ofek** [comment]
I can't wait to use that option, it looks awesome!

**Comment by abcbridge** [comment]
In case somebody needed to read about the workaround for omitting the years headings: 

To get rid of the year headings on the projects overview page, just comment them out in the project**s**.html layout file. 

Then, add fake dates to each project.md to allow them to be sorted the way you wanted them to be sorted.
