### ISSUE TITLE
404 Error when offline with service worker enabled

### ISSUE THREAD

**Issue by rriemann** [hydecorp/hydejack#119]
Hello,

you write in your docs:

> Other things to note are that the implementation will always cache the pages listed under legal, as well as the 404.html page, which will be shown when the user is offline.

Being offline is a client side problem. I think the displayed error message should reflect this. :)

Have a nice day!

**Comment by qwtel** [comment]
You are right. This is was a temporary solution that has become semi-permanent. Offline support is still experimental for a reason ;)

I was thinking about a `offline.html` or `598.html` (the status code I use in the SW to signal that the remote server is offline), or maybe add a string in `strings.yml` to let users customise the page.
