### ISSUE TITLE
Small typo in not-found.html

### ISSUE THREAD

**Issue by shawnyeager** [hydecorp/hydejack#122]
In https://github.com/qwtel/hydejack/blob/master/_layouts/not-found.html

"Sorry, we've misplaced that URL or it's pointing to something that doesn't exist."

Is missing a comma. Should be:

"Sorry, we've misplaced that URL, or it's pointing to something that doesn't exist."

**Comment by qwtel** [comment]
will fix. just in case you weren’t aware, you can use `strings.yml` to adjust it.
