### ISSUE TITLE
Sticky sidebar contents is not centered when resizing

### ISSUE THREAD

**Issue by harish64** [hydecorp/hydejack#136]
When we access the subpage directly using the URL,  sticky sidebar contents is not centered. Click on this link https://hydejack.com/docs/ and resize the window on a desktop to observe the behavior.

I think it is because  .cover is used as an anchor for transformations. I was able to fix this issue by

Adding  :

&.width-tracker {
      position: relative;
      width: 100%;
    }

Modifying sidebar.html from  class="{% if page.cover %}cover{% endif %}" to class="width-tracker {% if page.cover %}cover{% endif %}"

Not sure if this is the right way of fixing it.

**Comment by samuelpmish** [comment]
harish64, where did you place the &.width-tracker code? This is an annoying bug for sure.

**Comment by samuelpmish** [comment]
@harish64 , where did you place the &.width-tracker code? I'm trying to resolve this issue as well, and if you found a workaround, I'd love to copy it!

**Comment by harish64** [comment]
diff --git a/_includes/body/sidebar.html b/_includes/body/sidebar.html
index 6ebb5b1..0230ac1 100644
--- a/_includes/body/sidebar.html
+++ b/_includes/body/sidebar.html
@@ -1,5 +1,5 @@
 <hy-drawer
-  class="{% if page.cover %}cover{% endif %}"
+  class="width-tracker {% if page.cover %}cover{% endif %}"
   align="left"
   threshold="10"
   touch-events

diff --git a/_sass/hydejack/__inline__/_sidebar.scss b/_sass/hydejack/__inline__/_sidebar.scss
index ec66320..ed4f052 100644
--- a/_sass/hydejack/__inline__/_sidebar.scss
+++ b/_sass/hydejack/__inline__/_sidebar.scss
@@ -44,6 +44,11 @@ hy-drawer {
       position: relative;
       width: 100%;
     }
+
+    &.width-tracker {
+      position: relative;
+      width: 100%;
+    }

diff --git a/_sass/hydejack/_sidebar.pre.scss b/_sass/hydejack/_sidebar.pre.scss
index b38fad5..e484812 100644
--- a/_sass/hydejack/_sidebar.pre.scss
+++ b/_sass/hydejack/_sidebar.pre.scss
@@ -40,6 +40,11 @@ hy-drawer {
       position: relative;
       width: 100%;
     }
+
+    &.width-tracker {
+      position: relative;
+      width: 100%;
+    }
     // >>>

     // <<< link

**Comment by samuelpmish** [comment]
I'm sorry, but could you clarify more about where to put the snippet within the .css file? Also, these conversations support markdown formatting, so you can put   \`\`\`   before and after a block to get it to look more readable, for example, putting it around your comment gives:

```
index 6ebb5b1..0230ac1 100644
--- a/_includes/body/sidebar.html
+++ b/_includes/body/sidebar.html
@@ -1,5 +1,5 @@
<hy-drawer
`- class="{% if page.cover %}cover{% endif %}"`
`+ class="width-tracker {% if page.cover %}cover{% endif %}"`
align="left"
threshold="10"
touch-events

And add the corresponding class in the sidebar.css

&.width-tracker {
position: relative;
width: 100%;
}
```

**Comment by qwtel** [comment]
This is resolved now with the rewrite of hy-drawer in version 9
