### ISSUE TITLE
Tips on deploying pro version  (as a gem) with Netlify

### ISSUE THREAD

**Issue by funkypenguin** [hydecorp/hydejack#164]
Hey @qwtel - I'm working on deploying my site (PRO version) to Netlify, and I really like keeping my source clean by using the gem-based version of the pro theme, via SSH. Do you have any tips re how to do this using Netlify?

Thanks!
D

**Comment by rriemann** [comment]
I have my blog using netlify pro as gem hosted in a private gitlab repo and the blog source is on github:

https://github.com/rriemann/blog.riemann.cc/

I added to the Netlify environment the variable `BUNDLE_GITLAB__COM` which stores a gitlab-deploy-token, to allow bundler on Netlify to pull from the private gitlab repo.

This solution requires that you mirror your gitlab pro repo regularily.

Another solution is to build your blog locally and push the output directly to Netlify without building your blog remotely.

**Comment by shawnyeager** [comment]
I've been wanting to do the same with GitHub + Netlify. It seems that [this approach](https://community.netlify.com/t/common-issue-using-an-ssh-key-via-environment-variable-during-build/2457) in combination with access to the PRO gem via https will likely work. @qwtel, is that URL something you're able to provide?

**Comment by qwtel** [comment]
Personally what I would do is move the source files into a separate directory in the root of the repository, something that get's ignored by Jekyll by default, like `.hydejack-pro` or `_hydejack-pro` or `~hydejack-pro`. 

Then in `Gemfile` I'd point to the directory:

~~~yml
gem "jekyll-theme-hydejack-pro", path: './.hydejack-pro'
~~~

Don't forget to set `theme: jekyll-theme-hydejack-pro` in `_config.yml`.

**Comment by qwtel** [comment]
Anybody who wants to do this manually, this is the full `jekyll-theme-hydejack-pro.gemspec`

```yaml
# coding: utf-8

Gem::Specification.new do |spec|
  spec.name          = "jekyll-theme-hydejack-pro"
  spec.version       = "8.5.1"
  spec.authors       = ["Florian Klampfer"]
  spec.email         = ["mail@qwtel.com"]

  spec.summary       = %q{"Best Jekyll Theme by a Mile"}
  spec.homepage      = "https://hydejack.com/"
  spec.license       = "GPL-3.0"

  spec.files         = `git ls-files -z`.split("\x0").select { |f| f.match(%r{^(assets|_layouts|_includes|_sass|LICENSE|README)}i) }

  spec.required_ruby_version = "~> 2.2"

  spec.add_runtime_dependency "jekyll", "~> 3.7"

  spec.add_development_dependency "bundler", "~> 1.12"
  spec.add_development_dependency "rake", "~> 10.0"
end
```

**Comment by shawnyeager** [comment]
Thanks, @qwtel. I just shifted to the above approach, and it works nicely.
