### ISSUE TITLE
Auto dark mode in 8.5.x PRO

### ISSUE THREAD

**Issue by shawnyeager** [hydecorp/hydejack#176]
After upgrading to 8.5.1, I'm seeing a rendering problem with my site when my Mac is in Dark Mode under Mojave.

Here's a post on my site with Hydejack's dark mode disabled in `_config.yml` (as I prefer to have it), but MacOS dark mode on:

<img width="1222" alt="Screenshot 2019-08-24 23 51 32" src="https://user-images.githubusercontent.com/980297/63645745-82b36880-c6ca-11e9-8737-8ce5da839b06.png">

And here is the same post with Hydejack's dark mode enabled and MacOS dark mode on:

<img width="1219" alt="Screenshot 2019-08-24 23 50 59" src="https://user-images.githubusercontent.com/980297/63645759-d3c35c80-c6ca-11e9-8545-1dfcd7938bc8.png">

**Comment by qwtel** [comment]
I remember encountering a similar (if not the same) bug during development. I don't recall what exactly the fix was, but it was related to the CSS variables. Make sure you have all the lastest `dark-mode` files and aren't overriding them.

**Comment by shawnyeager** [comment]
I also tested on my branch using the 8.5.1 PRO gem (so no local `_includes`, `_js`, or `_sass`, but see the same behavior as above.

**Comment by qwtel** [comment]
Sorry, I didn't read your issue properly the first time. Yeah that's definitely a bug.

**Comment by qwtel** [comment]
the sunrise/sunset setting is ignored when the browser supports CSS prefers color scheme, so the dynamic setting is necessary to enable this feature
