### ISSUE TITLE
Moving to the latest version

### ISSUE THREAD

**Issue by MilovanTomasevic** [hydecorp/hydejack#178]
Exactly what folders / files should be replaced when upgrading from one version to the latest version?

You are progressing very quickly with code development, which is great, I mostly compared the code and changed those basic files from the update folder.

The question is how to quickly change the files so that I always go straight to the latest version.

Thank you so much for the quick answer, question because just because I enjoy your rapid development and I want my site to be always up to date.

**Comment by shawnyeager** [comment]
I suggest moving to the approach @qwtel suggest [here](https://github.com/hydecorp/hydejack/issues/164#issuecomment-526445722). It's working very nicely for me.

**Comment by MilovanTomasevic** [comment]
> I suggest moving to the approach @qwtel suggests [here](https://github.com/hydecorp/hydejack/issues/164#issuecomment-526445722). With this, you can
> 
> ```
> cd [your jekyll dir]/.hydejack-pro
> rm -Rf *
> cp -Rf [hydejack-pro release]/install/* .
> ```
> 
> And you're done.

since i already have my files like suxposts and media like pictures and recordings ... i dont have to go to someone else's posts like i commanded with it.  i need the part of the code that was done updating the latest version that is only related to functionality and does not include posts.  It only means some of the code I'm developing to improve the site, not the documentation and the like.  I have the entire content on my site.

**Comment by shawnyeager** [comment]
That’s the beauty of overrides. See [this](https://mmistakes.github.io/minimal-mistakes/docs/overriding-theme-defaults/) for a bit more detail.

**Comment by qwtel** [comment]
GitHub issues is for reporting issues, not opening service tickets.
