### ISSUE TITLE
Sidebar `accent_image` -> `background` won't refresh after back button

### ISSUE THREAD

**Issue by shawnyeager** [hydecorp/hydejack#179]
I was experimenting with adding `accent_image` -> `background` attributes to a project page, and observed that the sidebar does not change back to its default image/colors when using the Back button in Chrome v76 under MacOS Mojave. 

My default:

<img width="357" alt="Screenshot 2019-09-01 15 49 58" src="https://user-images.githubusercontent.com/980297/64082142-3ff81e80-ccd0-11e9-9038-08c169331587.png">

Sidebar while on project page with `accent_image` -> `background` copied from Hydejack PRO install:

<img width="356" alt="Screenshot 2019-09-01 15 50 11" src="https://user-images.githubusercontent.com/980297/64082150-5aca9300-ccd0-11e9-864c-895b8eb854ce.png">

Sidebar after Back button:

<img width="355" alt="Screenshot 2019-09-01 15 50 23" src="https://user-images.githubusercontent.com/980297/64082159-6a49dc00-ccd0-11e9-8b2a-11b011d8d242.png">

Any navigation within the site will cause this effect to remain. Only a browser refresh returns the sidebar to my defaults.

**Comment by qwtel** [comment]
Can you provide a more concrete example? I'm using the background property on hydejack.com and it seems to work fine there? E.g. https://hydejack.com/blog/hyde/2012-02-06-whats-jekyll/

**Comment by shawnyeager** [comment]
Will do. I’ll document further ASAP.

**Comment by qwtel** [comment]
V9 simplifies the page style process. Reopen if not resolved.
