### ISSUE TITLE
Font for code

### ISSUE THREAD

**Issue by MilovanTomasevic** [hydecorp/hydejack#180]
Add a parameter, e.g.

```yml
#file: _config.yml

font_code: Consolas, Courier, "Courier New", 'STKaiti', 'KaiTi', 'SimKai', monospace
```

then in the file `style.scss` add:

```css
$font-code: {{ site.font_code | default:"Noto Sans, Helvetica, Arial, sans-serif" }};
  
code        { font-family: {{ $font-code | default:"serif" }}; }
```

It would be nice to have that option in the next version as well.
This is one of the solutions for those who had no other solution, currently, and wanted to change the font for the code.

**Comment by qwtel** [comment]
Seems reasonable. Will be included in the next release

**Comment by MilovanTomasevic** [comment]
Tnx !
