### ISSUE TITLE
Grid post ?

### ISSUE THREAD

**Issue by MilovanTomasevic** [hydecorp/hydejack#181]
Does this seem useful and could it be in the next version?

![Screen Shot 2019-09-07 at 09 42 03](https://user-images.githubusercontent.com/26183601/64471576-ca6ad300-d153-11e9-9bc7-b4ed7fd1781a.png)

The [code](https://github.com/rstacruz/cheatsheets) from this [site](https://devhints.io/jekyll) is also on [githab](https://github.com/rstacruz/cheatsheets).

**Comment by qwtel** [comment]
that's an interesting layout, but seems to specific to be useful for hydejack. might revisit in the future.
