### ISSUE TITLE
support flow chart

### ISSUE THREAD

**Issue by i-mat** [hydecorp/hydejack#183]
Hope the theme can support flow chart just like the Markdown.
~~~markdown
```mermaid
graph LR
A[Hard edge] -->B(Round edge)
    B--> C{Decision}
    C-->|One| D[Result one]
    C-->|Two| E[Result Two]
```
~~~

**Comment by qwtel** [comment]
Can you be more specific what you expect, maybe provide a link? Vanilla markdown would not render this as a flow chart, not even a code block.

**Comment by PattonMT** [comment]
I use VScode (expanded with `Markdown Preview Enhanced`) to write `.md`，with the code below, It can display a flow chart on the page, just like [this](http://support.typora.io/Draw-Diagrams-With-Markdown/).
~~~markdown
```mermaid
graph LR
A[Hard edge] -->B(Round edge)
    B--> C{Decision}
    C-->|One| D[Result one]
    C-->|Two| E[Result Two]
```
~~~

I hope the theme can also display a flow chart with the code above.

**Comment by qwtel** [comment]
> Markdown Preview Enhanced

This is definitely not a standard markdown feature, but I agree that this would be interesting for a technical audience. I might look into it at some point.
