### ISSUE TITLE
Modifying the width of content

### ISSUE THREAD

**Issue by xu932** [hydecorp/hydejack#189]
I'm new to HTML/CSS and having trouble using the white space on the right side of blog/resume page.

I realize that there are a lot of white spaces on the right of content showing on those two pages and would like to use them for extra width for contents. I have tried to play with parameters in `_resume.scss` but it did not work as I intended to. I also tried `content-width` in `_variables.scss` and that does what I wanted (kind of) but it breaks the animation of the sidebar on resizing the window.

When the browser is wide, the side bar still occupies same relative portion of the window, yet the content extends to a point and stop extending. I would like the content also takes the entire remaining width if possible.

<kbd>![image](https://user-images.githubusercontent.com/15041478/68522032-cef75900-0274-11ea-899f-9e21e6cbc2ff.png)</kbd>

Can any one help me with this?

**Comment by qwtel** [comment]
I was actually just experimenting with ways in which to better utilize the extra space on large screens, potentially to include in a future release. However

> I would like the content also takes the entire remaining width if possible.

is not something I'll be supporting because long line lengths are bad for readability. Isolated content such as the project card would not be effected by this. The right column of the resume could benefit from *some* extra space.

> it breaks the animation of the sidebar on resizing the window

I think this is currently broken regardless of the value of `content-width`.

**Comment by xu932** [comment]
Thanks for confirming!

> > I would like the content also takes the entire remaining width if possible.
> 
> is not something I'll be supporting because long line lengths are bad for readability. Isolated content such as the project card would not be effected by this. The right column of the resume could benefit from _some_ extra space.

Personal opinion: I do think ling line length are bad for readability, but overall when the left side bar scales with the window width but not the content looks a bit weird to me. As a user, I prefer the radio to not change so much (on a wide screen the side bar is equally wide as the content). Those are my personal opinion and wish you take into consideration in future development.

**Comment by cgirerd** [comment]
> I was actually just experimenting with ways in which to better utilize the extra space on large screens, potentially to include in a future release.

Hello qwtel, I am also trying to find a way to use the white space on the right on large screens. I am thinking about small blocks arranged vertically, used to display news or other types of short content. These could then appear at the top or bottom at the page on small screens. Here is an example attach. Not asking for that in particular, just sharing my ideas :)
![right_space](https://user-images.githubusercontent.com/21290579/70888555-7adb4500-1f95-11ea-9fab-30b328a770de.png)

**Comment by qwtel** [comment]
Yes, it's similar to what I had in mind. One obvious example would be a table of contents. 

PS: The gradient on the side bar looks cool :) Would you mind if I included your site in an "examples"  page if I ever get around to making one? Link would be appreciated.

**Comment by cgirerd** [comment]
> Yes, it's similar to what I had in mind. One obvious example would be a table of contents.

That's a great idea!

> PS: The gradient on the side bar looks cool :) Would you mind if I included your site in an "examples" page if I ever get around to making one? Link would be appreciated.

Sure! And thanks again for your work! My website is [https://cgirerd.github.io](https://cgirerd.github.io). I am using this code for the gradient colors, with no overlay:
accent_image:
  background: 'linear-gradient(to bottom,#67AECA 0%,#675682 50%,#5F0F4E 100%)'

**Comment by qwtel** [comment]
In Hydejack 9 many variables such as content width can be modified using `_data/variables.scss` and all dependent properties should update outomatically (such as css variables, JS dependencies, etc.)
