### ISSUE TITLE
Side bar is not closed complety

### ISSUE THREAD

**Issue by techbless** [hydecorp/hydejack#196]
![image](https://user-images.githubusercontent.com/22078468/72211447-c3433f80-350e-11ea-96f7-619ec5ba06fa.png)

Like this image, Is the unfolded side bar intended?
If I want to close the side bar completely on the small display, How can I do for it?

**Comment by qwtel** [comment]
Yes, it’s intended to give an indication that there’s more content and to give an accent color to the page. 

I don’t think there’s an easy way to get rid of it at the moment, but I have some work in progress that should enable it.

**Comment by techbless** [comment]
Thank you!😀
