### ISSUE TITLE
Page build warning ???

### ISSUE THREAD

**Issue by MilovanTomasevic** [hydecorp/hydejack#208]
The page build completed successfully, but returned the following warning for the `master` branch:

You are attempting to use a Jekyll theme, "jekyll-theme-hydejack-pro", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/en/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll.

For information on troubleshooting Jekyll see:

 https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact?repo_id=157877591&page_build_id=181897529

**Comment by qwtel** [comment]
The problem is exactly what it says it is. 

I don't know how many times I've told you, the issue tracker is not a free-of-charge customer support forum.
