### ISSUE TITLE
Vulnerabilities discovered by Github Dependabot

### ISSUE THREAD

**Issue by shawnyeager** [hydecorp/hydejack#209]
I just turned on Github's Dependabot for kicks, and it notes the following as having 'moderate severity' vulnerabilities in the current versions shipped with hydejack.

<img width="827" alt="Screenshot 2020-06-21 21 13 19" src="https://user-images.githubusercontent.com/980297/85242253-21e8df80-b404-11ea-9c39-8fb8505f9323.png">

**Comment by qwtel** [comment]
You can most likely ignore these. In any case, in v9 these are updated and the warnings should be resolved
