### ISSUE TITLE
Feature request: SERP breadcrumbs

### ISSUE THREAD

**Issue by shawnyeager** [hydecorp/hydejack#214]
Low-priority, but would be a nice feature.

There doesn't appear to be much available on generating [Google SERP breadcrumbs](https://developers.google.com/search/docs/data-types/breadcrumb) with jekyll, but [this](https://jekyllcodex.org/without-plugin/breadcrumbs/) alludes to an approach.

**Comment by qwtel** [comment]
Yes, that would be nice, but I won't get to it anytime soon.

**Comment by shawnyeager** [comment]
Sweet. Thanks. 🙌🏼
