### ISSUE TITLE
Very small typo in _data/authors.yml + Any chance of adding new icon from icomoon?

### ISSUE THREAD

**Issue by LazyRen** [hydecorp/hydejack#215]
## Typo

In `_data/authors.yml` file,
```yml
  social:
    ......
    # keybase          <username>
```

should be

```yml
  social:
    ......
    # keybase:         <username>
```

It is measing ':' after keybase.

## Icomoon

Any chance of adding new icon 'profile' from the icomoon?
It looks like below.
![profile](https://user-images.githubusercontent.com/8989837/87227746-0015c380-c3d8-11ea-96a2-0738b3cc369f.PNG)

I've tried to create icomoon font by myself.
But couldn't find what options you used & hard to add only the icons you've added.

**Comment by qwtel** [comment]
Good catch. Thanks.

Yes, any icon you want :
https://hydejack.com/docs/advanced/#adding-a-custom-social-media-icon
