### ISSUE TITLE
Post title goes out of width boundary.

### ISSUE THREAD

**Issue by LazyRen** [hydecorp/hydejack#216]
I'm pretty confident (but not 100% sure) it wasn't like this in previous version 8.

As you can see from the below screenshots, the content of h1 header(post title) goes beyond the width of post itself.
Making layout very ugly.

I'm currently using 32:9 ultra-wide monitor, so I changed chorme's size in various way. It works fine in small width,
![c3](https://user-images.githubusercontent.com/8989837/87229615-699bcf00-c3e4-11ea-842d-ab1bb4f2bb60.PNG)

word-wrapping starts to break in middle width, (by one word goes out of the width boundary)
![c4](https://user-images.githubusercontent.com/8989837/87229616-6b659280-c3e4-11ea-9a89-5f13448f9c54.PNG)

and it completely breaks in wide width.

![c1](https://user-images.githubusercontent.com/8989837/87229552-d367a900-c3e3-11ea-9bfd-739991c01bbc.PNG)
![c2](https://user-images.githubusercontent.com/8989837/87229553-d5ca0300-c3e3-11ea-9ef6-d838a9ffe454.PNG)

**Comment by qwtel** [comment]
Feature, not a bug. 

Disable with `hydejack.no_large_headings`

There are more options in case you don't like content leaving the bounds.
