### ISSUE TITLE
Open sidebar links in a new tab?

### ISSUE THREAD

**Issue by Ptomerty** [hydecorp/hydejack#217]
Trying to serve static content (resume, etc.) from a personal site.

1. Setting `url:` to the local asset path (ex: `/assets/abc.pdf`) results in the site drawer opening before the site loads.

2. Setting `url:` to the fully qualified URL results in nothing happening if you attempt to click to open the link, and the asset loading correctly if you open it in a new tab.

Thus, it would be nice if there was an option to open sidebar links in a new tab so that static asset delivery (and link opening) could work correctly. Thanks!

**Comment by Ptomerty** [comment]
Resolved; used a sidebar icon instead.

**Comment by Ptomerty** [comment]
Sorry for re-opening; I can recreate this issue with the default `download:` tag in `_data/authors.yml`. When clicking to open/download on a GH Pages-hosted site, the slide bar will open before leading you to the link.

On version v9.0.3.

**Comment by qwtel** [comment]
I'll add a `external` option that will prevent closing the drawer (and add the external icon in case that option is enabled):

```yml
menu:
  - title: Resume
    url: /assets/Resume.pdf
    external: true
```

However, this will not force opening in a new tab! As far as I can see, there's no good reason to (c.f. https://css-tricks.com/use-target_blank/), but you can add this functionality on your own using `_includes/my-body.html`

**Comment by qwtel** [comment]
Unfortunately this didn't make it into 9.0.4. Will be in the next release. This issue will be closed when it lands

**Comment by Ptomerty** [comment]
Looking forward to it! Thanks :)

**Comment by brainomite** [comment]
I would love it if this could be more generalized and say any/all external links open in a new tab, or give us a way on a link-by-link basis

**Comment by Ptomerty** [comment]
For posts, you can use kramdown syntax; just append `{target="_blank"}`
after your link.

**Comment by codebloded** [comment]
use this syntax within the anchor tag  `{target="__blank"}`
