### ISSUE TITLE
Reference to invalid URL

### ISSUE THREAD

**Issue by shawnyeager** [hydecorp/hydejack#222]
Just ran a link-checker, and the following now generate a 404:

```
  <link rel="dns-prefetch" href="https://fonts.googleapis.com">
  <link rel="dns-prefetch" href="https://fonts.gstatic.com">
```

**Comment by qwtel** [comment]
They've probably always returned a 404. The point of these links is to perform DNS resolution ahead of time, to speed up font loading later. Maybe the link checker isn't interpreting the `dns-prefetch` rel properly.
