### ISSUE TITLE
How To Configure Displayed Blog Post Metadata

### ISSUE THREAD

**Issue by AntsInMyEy3sJohnson** [hydecorp/hydejack#224]
Hi everyone,

I've been playing around with Hydejack recently, loving it so far. Now I have a question I have been unable to figure out for myself:

# Context
I have a bunch of blog posts that use the _blog_ layout, i. e. there is an _index.html_ file contained in their root directory, as explained [in this piece of documentation](https://hydejack.com/docs/config/#using-the-blog-layout-in-a-subdirectory). Because I want to write blog posts on different topics, posts on one topic go into a dedicated directory sitting at the Jekyll root (for example, _[root]/software-engineering_. Each post has a `category` configured in its Front Matter, as well as a couple of `tags`.

# Problem
The default behavior for how blog post metadata gets generated seems to work like so:

_[date] in [local folder] / [category] on [list of all tags]_

In my case, this yields something like the following:

_28 Jul 2020 in Software-engineering / Software engineering on Software systems, Orthogonality, Coupling, Cohesion_

_Software-engineering_ is not spelled like this in English, and I also don't like how the first word in each tag is capitalized, but the second one isn't. Therefore:

# Question
How can I configure the way the blog post metadata is created? Most importantly, I'd like to disable the inclusion of the local directory within the metadata because that couples the underlying folder structure to the way the content stored therein is presented to readers -- a coupling that, in my opinion, is undesirable.

**Comment by qwtel** [comment]
﻿You can create a featured category (see docs) and give it an arbitrary name.

https://hydejack.com/docs/basics/#adding-a-category-or-tag

**Comment by AntsInMyEy3sJohnson** [comment]
Cool, this has solved my problem. Thanks!
