### ISSUE TITLE
Tab bar icon

### ISSUE THREAD

**Issue by saching13** [hydecorp/hydejack#227]
![image](https://user-images.githubusercontent.com/43363595/90304977-32e92680-de72-11ea-9b5d-1fc6931503e6.png)

Is it possible to change they HY on tab icon to our own pic or something ?

**Comment by qwtel** [comment]
Yes, replace `assets/icons/favicon.ico`. 

To also replace "Install to Homescreen" icons, see https://hydejack.com/docs/config/#adding-custom-favicons-and-app-icons

**Comment by saching13** [comment]
is that only for pro version ? because I I have assets/img/.. but I don't have any icons folder under assets. Should I just create one ? Sorry for all these questions. I am new to this.

**Comment by qwtel** [comment]
yes, just create. also be mindful of browser cache. it gets easily stuck with outdated favicons

**Comment by saching13** [comment]
Sure. Will do that. Thanks alot for the help and an amazing template.
