### ISSUE TITLE
Is the Pro version not compatible with GitHub Pages?

### ISSUE THREAD

**Issue by AfzalivE** [hydecorp/hydejack#234]
I updated from free version 8.5.2 to PRO 9.0.4 and everything was working on my local but I'm just getting a white page on my website with Page build failures that aren't telling me anything. I experimented a little with the GitHub Pages section of the documentation but no luck.

I'm not really looking for support but looking to confirm whether PRO + Github pages actually works or not. Thanks and thank you for making this brilliant theme!

**Comment by qwtel** [comment]
It does work but unfortunately not out of the box. GH pages does not support a separate theme folder. The contents of `#jekyll-theme-hydjeack` need to be merged with the containing folder and `theme` key in `_config.yml` needs to be removed.

**Comment by AfzalivE** [comment]
I'm going to see if I can use Github actions to build it instead of Github pages using this guide:

https://jekyllrb.com/docs/continuous-integration/github-actions/
