### ISSUE TITLE
[Request] A frontmatter flag to exclude a post from search

### ISSUE THREAD

**Issue by AfzalivE** [hydecorp/hydejack#237]
It would be useful to add a frontmatter flag to exclude a post from the built-in search index.

Something like this perhaps:
https://idratherbewriting.com/documentation-theme-jekyll/mydoc_search_configuration.html

That theme uses `search: exclude` for this.

~~I could submit a PR for this if you want.~~

Apparently, the search code is in the Pro version, so I guess I cannot submit a PR. It's like 3 lines of change though. One in search_worker.js to filter the documents, and one in sitedata.json to include the "search" frontmatter.

**Comment by qwtel** [comment]
You can currently remove a page from search by setting `sitemap: false`, but this will also remove it from the site map.

**Comment by AfzalivE** [comment]
I'll double-check but it didn't work for me when I tried earlier with drafts. I do have a slightly weird setup where I override the use drafts as a collection to be able to link the post to people but still have it not show up on the main blog or built-in search.

**Comment by qwtel** [comment]
Fixed in 9.1.0
