### ISSUE TITLE
[Feature Request] grid layout in a subfolder

### ISSUE THREAD

**Issue by brainomite** [hydecorp/hydejack#238]
We can presently do a [blog layout in a subfolder](https://hydejack.com/docs/config/#using-the-blog-layout-in-a-subdirectory). For those of us using the pro version, it'd be nice to have the grid as an option for a subfolder.

**Comment by brainomite** [comment]
Actually I can't figure out even how to add a post when using the blog layout in a subfolder

**Comment by qwtel** [comment]
You can use the grid layout in a subfolder, e.g. https://hydejack.com/posts/ (corresponding file; https://github.com/hydecorp/hydejack-site/blob/master/posts.md). Jekyll only has a single collection for posts, so adding posts is the same regardless of the layout and location of the site.

**Comment by brainomite** [comment]
Ahhh, single collection, that is unfortunate; thank you for the heads up. I guess I'll start a second blog on a subdomain! Thanks for the help!!

**Comment by qwtel** [comment]
It is a single collection, but you can slice it up via categories and tags. For more see here: https://hydejack.com/docs/basics/#adding-a-category-or-tag
