### ISSUE TITLE
Include .script folder & package.json for starter-kit

### ISSUE THREAD

**Issue by LazyRen** [hydecorp/hydejack#240]
[hydejack-starter-kit](https://github.com/hydecorp/hydejack-starter-kit) and downloadable files from pro version's starter-kit doesn't come with the `.script` folder & `package.json`. Yet, [docs](https://hydejack.com/docs/advanced/#how-css-is-organized-in-hydejack) suggest that we must use it to change `css` of the theme. (Which is true, I had to manually change `.scss` files since I couldn't build it).

I believe those folder & files must be included into the starter-kit as well as gh-page version, so people can use it to change `css`.
I had to re-download pro version and look for the missing piece by myself to figure out why `npm run build:css` doesn't even work as described in the doc.

Thank you.

**Comment by qwtel** [comment]
Oh yeah, that should be included. In the meantime please use the files from the free version (they are identical): https://github.com/hydecorp/hydejack/tree/master/.scripts

**Comment by qwtel** [comment]
This should be fixed in 9.1.

**Comment by joshuajaharwood** [comment]
.scripts and package.json still aren't included in gh-pages folder in pro release. Is this as intended? Having to take a copy from the standard folder.

**Comment by qwtel** [comment]
You are correct. Only the essential folders (_includes, _layouts, _sass and assets) are copied over to the gh-pages starter  kit. If you want to customize the build from there, you'll have to manually copy the scripts, package.json etc from the jekyll-theme-hydejack folder.

**Comment by qwtel** [comment]
You are correct. Only the essential folders (_includes, _layouts, _sass and assets) are copied over to the gh-pages starter  kit. If you want to customize the build from there, you'll have to manually copy the scripts, package.json etc from the jekyll-theme-hydejack folder.
