### ISSUE TITLE
[Request] Remove console.log branding in pro

### ISSUE THREAD

**Issue by brainomite** [hydecorp/hydejack#248]
For the pro version, can you please remove the HydeJack branding from the console.log? 
Whereas we have an option for the webpage content, we don't have it for the console.

![image](https://user-images.githubusercontent.com/11599888/105647362-1e727680-5e73-11eb-9879-9ba59e561ad6.png)

**Comment by qwtel** [comment]
Seems reasonable. Will do

**Comment by qwtel** [comment]
Fixed in 9.1.0
