### ISSUE TITLE
[Request] Remove hydjack branding from html files on pro

### ISSUE THREAD

**Issue by brainomite** [hydecorp/hydejack#249]
My last request, I'll not ask for it to be removed from the JS files. 

Software Engineer hiring managers often peak at the HTML behind sites.
Could you remove the branding on the HTML for the pro version?

![image](https://user-images.githubusercontent.com/11599888/106021164-83f07e00-6092-11eb-9d70-afbfd7a7a00f.png)

**Comment by qwtel** [comment]
Fixed in 9.1.0
