### ISSUE TITLE
[bug] in Pro 9.1.0 Copy Code button has no icon

### ISSUE THREAD

**Issue by brainomite** [hydecorp/hydejack#251]
Awesome job on the update!

1. While the copy button works, there's no icon representing it.
2. Without the filename header it's practically invisible.

![image](https://user-images.githubusercontent.com/11599888/107082144-c0725700-67c1-11eb-8ffb-f0ef37dd21fc.png)

![image](https://user-images.githubusercontent.com/11599888/107081458-b734ba80-67c0-11eb-843c-3a7822ba69c0.png)

**Comment by brainomite** [comment]
Alright, I figured out one of the issues!

1. I had copied icomoon folder over as I had modified my icomoon previously, it's clearly missing the new icons. I will make a new one.
2. The behavior when the filename isn't present is only to display copy icon on hover.

**Comment by qwtel** [comment]
> The behavior when the filename isn't present is only to display copy icon on hover.

Correct, because without the header it can easily overlap with a long first line.
