### ISSUE TITLE
Hide 'clap' always?

### ISSUE THREAD

**Issue by shawnyeager** [hydecorp/hydejack#253]
Great update, @qwtel. Thanks.

Is there a way to hide the clap button always? I'd rather not see it locally or in prod. I tried `clap_button: false` in `_config.yml`, but that doesn't appear to work.

Cheers.

**Comment by chiselwright** [comment]
I think it's intentionally "always on" outside production, looking at https://github.com/hydecorp/hydejack/blob/master/_includes/head/scripts.html#L14

```
w._clapButton = {% if site.clap_button or jekyll.environment != 'production' %}true{% else %}false{% endif %};
```

seems to indicate that if you set it to `false` it'll fall through to "oh, we're not production" and it's set to `true`.

I suspect this is to showcase the feature locally.

**Comment by LazyRen** [comment]
Removing `jekyll.environment != 'production'` from `_includes/components/dingbat.html` & `_includes/head/scripts.html` will do.

**Comment by qwtel** [comment]
> I suspect this is to showcase the feature locally.

Yes, that is the point. 

Supporting `clap_button: false` seems like a good idea though.

**Comment by qwtel** [comment]
Added in 9.1.1 (PRO only)

**Comment by chiselwright** [comment]
I think you have accidentally bundled non-Pro as Pro.

I bought and used 9.1.0 over the weekend and it has:

```sh
# 9.1.0
❯ /bin/ls \#jekyll-theme-hydejack/_layouts
about.html  blog.html      default.html  home.html  not-found.html  page.html   post.html     projects.html  resume.html
base.html   compress.html  grid.html     list.html  offline.html    plain.html  project.html  redirect.html  welcome.html
```

I downloaded this morning, to continue working on a different machine, picked up pro-9.1.1 and starting up I see:

```text
     Build Warning: Layout 'grid' requested in _featured_categories/blog.md does not exist.
     Build Warning: Layout 'grid' requested in _featured_categories/tech.md does not exist.
     Build Warning: Layout 'welcome' requested in index.md does not exist.
     Build Warning: Layout 'resume' requested in resume.md does not exist.
```

This is what's in `_layouts`:

```sh
❯ /bin/ls ~/Desktop/hydejack-pro-9.1.1/\#jekyll-theme-hydejack/_layouts
about.html	blog.html	default.html	list.html	page.html	post.html
base.html	compress.html	home.html	not-found.html	plain.html	redirect.html
```

Would you prefer this as a new issue?

**Comment by shawnyeager** [comment]
@qwtel: I just updated to 9.1.1 and added `clap_button: false` to `_config.yml`, but I'm still seeing the clap block.

**Comment by qwtel** [comment]
> I think you have accidentally bundled non-Pro as Pro.

Yes I did. I noticed shortly after and re-uploaded it.

**Comment by shawnyeager** [comment]
> @qwtel: I just updated to 9.1.1 and added `clap_button: false` to `_config.yml`, but I'm still seeing the clap block.

Just to confirm, this is still not functioning as designed.

**Comment by rriemann** [comment]
Please reopen the issue, `clap_button: false` does not do the trick and please document if this goes into the `hydejack` dictionary or not.
