### ISSUE TITLE
v9.1.0: Drawer redraw after dismissing print dialog

### ISSUE THREAD

**Issue by shawnyeager** [hydecorp/hydejack#254]
Under Chrome Version 88.0.4324.146 (Official Build) (x86_64), after dismissing the Print dialog triggered from a resume page, the drawer content is erased.

**Comment by qwtel** [comment]
This is most likely a chrome bug. I'm not sure there's even a "print dialog closed" event, making even workarounds hard to do. 

Note that the content appears as soon as interacting with the sidebar in any way.
