### ISSUE TITLE
v9.1.0: date + tag/category line wrap

### ISSUE THREAD

**Issue by shawnyeager** [hydecorp/hydejack#255]
I'm noticing that this line no longer wraps on mobile, both in Safari and Chrome.

![image](https://user-images.githubusercontent.com/980297/107120326-56bf7f00-688d-11eb-88f9-dbd400579cc8.jpeg)

**Comment by qwtel** [comment]
I see. This was done on purpose to fix an issue with the animation.

The fix I have in mind it to properly clip the text:

<img width="689" alt="Screenshot 2021-02-08 at 10 50 19" src="https://user-images.githubusercontent.com/951987/107173910-89878580-69fb-11eb-9c12-b2d69a5fb445.png">

**Comment by qwtel** [comment]
and add a tooltip for long lines/mobile
<img width="358" alt="Screenshot 2021-02-08 at 11 04 16" src="https://user-images.githubusercontent.com/951987/107174730-85f4fe00-69fd-11eb-9ac5-d7a3f5c4680d.png">

**Comment by shawnyeager** [comment]
Looks great. Thanks.

**Comment by qwtel** [comment]
Added in 9.1.1

**Comment by shawnyeager** [comment]
@qwtel: Looks good. Is it the intended behavior that a click is required to see the tooltip, rather than just hovering? I don't see it when I hover the pointer, but I do when I click. Maybe a Chrome thing?

**Comment by qwtel** [comment]
Yes. On mobile (where the text is most likely to be cut off) a tap is necessary anyway, and on larger screens I want it to be close to the old behaviour.
