### ISSUE TITLE
posts_page doesn't work in welcome.html

### ISSUE THREAD

**Issue by chiselwright** [hydecorp/hydejack#259]
I've _only_ looked at `posts_page`, I haven't tried any of the other options in the file.

Jekyll 4.2.0; relies on the localised version mentioned in https://github.com/hydecorp/hydejack/issues/258

I've had real trouble getting it to match anything, and after some investigation I believe that this is the required change:

~~~patch
diff --git a/#jekyll-theme-hydejack/_layouts/welcome.html b/#jekyll-theme-hydejack/_layouts/welcome.html
index b3a9e43..26dcbaf 100644
--- a/#jekyll-theme-hydejack/_layouts/welcome.html
+++ b/#jekyll-theme-hydejack/_layouts/welcome.html
@@ -101,7 +101,7 @@ layout: about
 {% assign posts_page = page.posts_page | default:page.more_posts %}
 {% if posts_page %}
   {% if major >= 4 and minor >= 1 %}
-    {% assign more_posts = site.pages | find_exp:"page", "posts_page == page.path or posts_page == page.url" %}
+    {% assign more_posts = site.documents | find_exp:"page", "posts_page == page.path or posts_page == page.url" %}
   {% else %}
                            {% assign more_posts = site.pages | where_exp:"page", "posts_page == page.path" | first %}
     {% unless more_posts %}{% assign more_posts = site.pages | where_exp:"page", "posts_page == page.url"  | first %}{% endunless %}
~~~

for this to work:

~~~md
---
layout: welcome
title:  chisel's place
cover:  true
posts_page: /blog/
---

<!--author-->

## Recent Posts

<!--posts-->
~~~

with this featured category:

~~~md
---
layout: grid
title:  Blog
slug:   blog
description: >
  Sometimes ideas just need writing down.
---
~~~

**Without** this change, I see:

```
Page with path <code></code> not found.
```

**With** this change, I see (the expected):

```
See Blog for more
```

**Comment by qwtel** [comment]
Ah I see. Jekyll doesn't treat the `blog` layout as a page, which is why it's missing. However, `site.documents` only solves the problem for your specific case. What's missing is a collection of all pages _and_ documents, that Jekyll doesn't provide by itself. Using this in 9.1.2:

    {% assign nodes = site.html_pages | concat: site.documents %}

**Comment by chiselwright** [comment]
Thanks for this. I had a feeling this wasn't 100% correct in the general case, but couldn't fully get my head round the problem space.
