### ISSUE TITLE
Question: Is there a any easy way to upgrade PRO version?

### ISSUE THREAD

**Issue by LazyRen** [hydecorp/hydejack#260]
Since Hydejack PRO is not supported via Github (rather pure zip file), I'm having hard time updating when new version is came out.

What I did so far was 100% handcrafting with help of VS Code diff tool. Which feels... very stupid. (Especially since I have some minor files changed so I can't just drag-and-drop the files. And yet there is so many diffs simply because of version string diffs.)

How others handle this situation?

**Comment by qwtel** [comment]
Can't you just replace the entire `#jekyll-theme-hydejack` folder? Or would that overwrite your cutomizations?

**Comment by LazyRen** [comment]
It will overwrite customizations. & I already merged all contents to the root. (Failed to make it work `#jekyll-theme-hydejack` with gh-pages. )

**Comment by rriemann** [comment]
> How others handle this situation?

I have two repos:

1. The Jekyll-powered blog at https://github.com/rriemann/blog.riemann.cc
2. A private repo with the pro template linked in the `Gemfile`:

~~~ruby
gem "jekyll-theme-hydejack-pro", git: 'https://gitlab.com/rriemann/hydejack-pro.git', branch: 'gem-pro'
~~~

Netlify Free plan pulls after every push, builds the blog and publishes it. For authentication to the private blog, I use git http access tokens: see [gitlab docs](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html) and check out the ENV variable to be configured in Netlify `GITHUB_TOKEN` or `GITLAB_COM_TOKEN`.

**Comment by shawnyeager** [comment]
@rriemann's approach is what I was initially aiming for, but I wasn't able to sort out access tokens between GitHub and Netlify; may need to revisit.

So, I settled on the following in my `Gemfile`:

`gem "jekyll-theme-hydejack", path: "./#jekyll-theme-hydejack"`

And simply replacing this directory, wholesale, with each new release. Less elegant, but it works for me.

**Comment by LazyRen** [comment]
Does Gemfile works for the github-pages as well?

AFAIK, github-pages does not look into `Gemfile` or `Gemfile.lock`. It only inspect `_config.yml`.
Which was the reason why I removed `#jekyll-theme-hydejack` & brought all files to the root folder even after Hydejack v9 came out.

...and probably the reason for starter-kits of Hydejack not having `#jekyll-theme-hydejack`.

Even if it does work, I cannot simply copy-and-paste it. It will remove all my personal changes to the theme.

Thanks @rriemann @shawnyeager for providing your way. I liked the idea of having two repos :)
