### ISSUE TITLE
jekyll empty slug warnings caused by resume generator?

### ISSUE THREAD

**Issue by shawnyeager** [hydecorp/hydejack#262]
Having commented on [this jekyll issue](https://github.com/jekyll/jekyll/issues/8259), I finally got around to capturing standard out and error to track this down. Here's what I found:

```
         Rendering: cv.md
  Pre-Render Hooks: cv.md
  Rendering Markup: cv.md
Post-Convert Hooks: cv.md
  Rendering Layout: cv.md
[33m           Warning: Empty `slug` generated for ''.[0m
[33m           Warning: Empty `slug` generated for ''.[0m
[33m           Warning: Empty `slug` generated for ''.[0m
[33m           Warning: Empty `slug` generated for ''.[0m
```

Note: `cv.md` is just my renamed `resume.md`.

**Comment by qwtel** [comment]
Fixed in 9.1.3

**Comment by shawnyeager** [comment]
@qwtel I still seed the same errors on build with 9.1.4.

**Comment by qwtel** [comment]
I'm testing for null values, so removing the `level` or `fluency` entry entirely will prevent the warning in 9.1.4. 

In an upcoming version I'll test for empty strings as well.
