### ISSUE TITLE
Question:How can I change the URL“https://fonts.googleapis.com/“?

### ISSUE THREAD

**Issue by buffzhou** [hydecorp/hydejack#264]
”https://fonts.googleapis.com/css?family=Roboto+Slab:400|Noto+Sans:400,400i,700,700i“ can‘t be  visited in China.
How can I change it to ”fonts.useso.com“?
THX！

**Comment by qwtel** [comment]
Oh, it's not possible to change it right now, but seems like I should add that feature as soon as possible.

**Comment by rriemann** [comment]
I used https://google-webfonts-helper.herokuapp.com/fonts to download the fonts and host them in the `/assets/fonts` folder. I included the css files for the fonts in the scss of the blog.

**Comment by qwtel** [comment]
The google fonts provider can now (9.1.3) be configured:

> Allow setting custom Google Fonts providers via `google_fonts_url`. Defaults to `https://fonts.googleapis.com`.
