### ISSUE TITLE
clap_button: true

### ISSUE THREAD

**Issue by OptogeneticsandNeuralEngineeringCore** [hydecorp/hydejack#265]
In config file, you may wish to list: clap_button: true, as suggested by "To use Clap Button on your site, get a <a href="https://getclaps.app#pricing">subscription</a><br/>and set <code>clap_button: true</code> in your config file.</span>"

**Comment by qwtel** [comment]
Thanks for the suggestion. Unfortunately clap button has been a failure and I will remove all mention in an upcoming version.
