### ISSUE TITLE
Liquid Warning

### ISSUE THREAD

**Issue by MilovanTomasevic** [hydecorp/hydejack#271]
When I want to writing (with ``` ) the `highlight code` in my post, I get a warning:

```js
<script src="{{ static_url('index.js') }}" type="text/javascript"></script>
```

warning:
```sh
Liquid Warning: Liquid syntax error (line 93): Expected end_of_string but found open_round in "{{ static_url('index.js') }}" in PATH/TO/MD_FILE
```

the current solution is:
```md
{% raw %} code {% endraw %}
```
How would I solve that considering that it is the only warning I have?

Thanks for the reply.
M

**Comment by LazyRen** [comment]
That's because Liquid tries to run the code with liquid syntax( ```{{ }}```).

I think your current solution is the only solution you can get.  I also uses the same solution.
Tho I prefer to use

```
{%- raw -%}
code
{% endraw %}
```

to prevent unnecessary blank line.
