### ISSUE TITLE
Invalid US-ASCII character "\xE2" on line 6 in assets/css/hydejack-9.1.4.css

### ISSUE THREAD

**Issue by freegroup** [hydecorp/hydejack#276]
Hi,
bought the PRO version today and I got the error below after an `bundle install` and `bundle exec jekyll serve` .

Any idea how to fix this?

**Comment by LazyRen** [comment]
Are you sure you have not added any character into the file by mistake?

Just in case, here is the full content of the file.

```default
---
---
{% capture include_to_scssify %}{% include styles/style.scss %}{% endcapture %}{% include header.txt %}{{ include_to_scssify | scssify }}
```

**Comment by freegroup** [comment]
delete the vendor folder and reinstall everything fixed this issue.
sorry for the noise and thanks for your support.
