### ISSUE TITLE
now is not "jekyll-theme-hydejack" supported by GitHub Pages?

### ISSUE THREAD

**Issue by khw11044** [hydecorp/hydejack#284]
The page build completed successfully, but returned the following warning for the `master` branch:

You are attempting to use a Jekyll theme, "jekyll-theme-hydejack", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://docs.github.com/github/working-with-github-pages/adding-a-theme-to-your-github-pages-site-using-jekyll.

For information on troubleshooting Jekyll see:

  https://docs.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request at https://support.github.com/contact?repo_id=399145155&page_build_id=274590295

i got this email... and my blog can not host it

**Comment by qwtel** [comment]
This is correct. Supported themes on GitHub Pages are very limited. To use Hydejack on GitHub Pages, follow this steps: https://hydejack.com/docs/install/#github-pages
