### ISSUE TITLE
breadcrumb shows .html suffix

### ISSUE THREAD

**Issue by garymm** [hydecorp/hydejack#286]
Is there a way to get the breadcrumb to not show the `.html` suffix for the current page?

Aside: Is there any way to disable the breadcrumbs entirely? (I can open another issue for this if desired)

Thanks!

**Comment by qwtel** [comment]
the suffix is determined by the `permalink` property (see jekyll docs for reference)

> Is there any way to disable the breadcrumbs entirely

yes, Disable with `hydejack.no_breadcrumbs` in config.yml
