### ISSUE TITLE
Code Blocks and Other Elements Wider Than Main Document

### ISSUE THREAD

**Issue by mthbrown** [hydecorp/hydejack#288]
Hi,

Is it just me or does it look strange that code blocks and other elements overflow to the left and right compared to your main content? For example: https://hydejack.com/docs/writing/#adding-code-blocks 

![Screen Shot 1](https://user-images.githubusercontent.com/22183215/135782476-0dafbec3-9109-4480-84fe-541f957afb84.png)

![Screen Shot 2](https://user-images.githubusercontent.com/22183215/135782490-33be35af-7a57-44b2-9115-1198417c390d.png)

Notice how the code block and the table are wider than the text before and after them, which doesn't look aesthetically correct. Is there any way to enforce that all elements don't overflow like this? Thanks

**Comment by qwtel** [comment]
A matter of taste I would say, by can be disabled by setting 

```yml
hydejack:
  no_break_layout:     true
```

in config.yml

**Comment by mthbrown** [comment]
I was able to solve most of the issues by modifying  CSS attributes in `_sass/pooleparty/__link__/_code.scss` but I'm curious if I'm the only one who thinks aligning these elements with the main text looks better or the default looks better

**Comment by mthbrown** [comment]
I might not have been clear. From my testing, the mentioned setting isn't what causes this. For example, with the above setting set `true`, I would still end up with this:

![hydejack_with_and_without_setting](https://user-images.githubusercontent.com/22183215/135938159-87a2a4bb-fab1-4ee5-833e-3f763569d05b.png)

When set to `false`, I would end up with this:

![hydejack_false](https://user-images.githubusercontent.com/22183215/135938473-818a229e-9e41-4f8d-8380-97d254412bf3.png)

On the other hand, if I modify `_code.scss` and update `.figure-base` by commenting out the `margin-left` and `margin-right` lines, it aligns correctly as shown below:

![hydejack_with_custom_code](https://user-images.githubusercontent.com/22183215/135938177-91c1ac7f-c1ed-4481-a10d-0c43a0e5925e.png)

Notice how it is now aligned with the text. Thanks
