### ISSUE TITLE
Question: change color of all the main pages

### ISSUE THREAD

**Issue by renswilderom** [hydecorp/hydejack#290]
Hello Hydejack builders! I like to change the color of all the main pages (i.e. the large colomn on the righthand side of, for example, the home page and the blogposts).

I managed to change the color of the side bar. While I tried many things for the color of the main pages, it didn't work (e.g. I changed the theme_color in the _config file [see below] but without positive results). 

Your help will be much appreciated!

https://renswilderom.github.io/

```
defaults:
  # You can use this to provide a default accent color and background for
  # all pages under a given path:
  - scope:
      path:            hyde/
    values:
      accent_color:    rgb(38,139,210)
      theme_color:     rgb(253, 251, 236)
      # theme_color:     rgb(38,139,210)

      accent_image:
        background:    rgb(253, 251, 236)
        # background:    rgb(32,32,32)

        overlay:       false
```

**Comment by qwtel** [comment]
Hi, I haven't designed with this in mind, but you can try changing the CSS variable via custom css (check documention, or add to `_sass/my-inline.scss` something like: 

```css
html {
  --body-bg: #efefef;
}
```

Can't guarantee that this won't lead to visual artifacts though. Good luck

**Comment by qwtel** [comment]
I've just tried this myself, it looks better if you also change `--border-color`, e.g.:

```css
html {
--body-bg: #ddd;
--border-color: #bbb;
}
```

Full list of css variables that can be overwritten:

<img width="370" alt="Screenshot 2021-11-19 at 15 32 30" src="https://user-images.githubusercontent.com/951987/142591065-fc75baaa-c290-4e55-807a-b89eed7a4837.png">

**Comment by renswilderom** [comment]
Thank you, Florian! It works and while I may fine tune it later, Im very happy with the result for now (see picture). 

![image](https://user-images.githubusercontent.com/27849748/142603692-84dd0c68-d398-44c1-983f-cf0fc7f42643.png)


As mentioned in the documentation, with custom inline scss the build time becomes slower. So I will build first, and then put the customization on. 

Thanks, and I love theme that you guys build!

**Comment by danielecampli-unitrento** [comment]
Is the suggested workaround still working? 

> I've just tried this myself, it looks better if you also change `--border-color`, e.g.:
> 
> html {
> --body-bg: #ddd;
> --border-color: #bbb;
> }
> Full list of css variables that can be overwritten:
> 
> <img alt="Screenshot 2021-11-19 at 15 32 30" width="370" src="https://user-images.githubusercontent.com/951987/142591065-fc75baaa-c290-4e55-807a-b89eed7a4837.png">

I have tried to put the content above in the file `_sass/my-inline.scss`, but it does not work.
