### ISSUE TITLE
Building on GitHub Pages doesn't work anymore

### ISSUE THREAD

**Issue by fasterius** [hydecorp/hydejack#296]
First, thanks for a great theme! I've used it for a couple of months now, and I just added some new content to my website that is hosted on GitHub pages. It doesn't work anymore, though, and I'm getting an error in the build:

`github-pages 223 | Error:  The jekyll-theme-hydejack theme could not be found.`

It worked before, and I changed nothing except adding more content to one of my markdown files. I tried to update `remote_theme` to `9.1.6` (I previously had `9.1.4`), but it didn't make a difference. My build and its errors can be found here: https://github.com/fasterius/fasterius.github.io/actions/runs/1805605863. Any idea what is wrong? I assume I've forgotten to do something, but I thought it would have worked, since it did before.

**Comment by qwtel** [comment]
Hi, thanks for reporting this. 

Most likely related to the release just now 🙁

If you hard-code the dependency back to `@v9.1.4` it should work as before?

**Comment by fasterius** [comment]
It didn't work when I had `@9.1.4` in the `remote_theme` either; my updating of it was something I tried after it failed, just as something that felt obvious to me to try. Anything else I can try?

**Comment by qwtel** [comment]
I notice you use both `theme` and `remote_theme`. With github pages it should only be `remote_theme`.

**Comment by fasterius** [comment]
Oh, okay! Yes, reverting to `9.1.4` and removing `theme` (keeping only `remote_theme`) worked! Thanks a lot for the quick help :-D

**Comment by qwtel** [comment]
I think using 9.1.6 should be save too. I have a successful gh pages build with it [here](https://github.com/hydecorp/hydejack-starter-kit/actions/runs/1804627257)

**Comment by fasterius** [comment]
Yes, I just tested, it works as well. Thanks again!
