### ISSUE TITLE
[Question] How can I control background of the sidebar?

### ISSUE THREAD

**Issue by prettygood236** [hydecorp/hydejack#298]
![Screenshot from 2022-03-06 20-44-03](https://user-images.githubusercontent.com/96720683/156921667-8d0cc753-92e9-41dd-b7ce-24ff5f846a13.png)

How can I get rid of the black line in the middle of the background of the sidebar? (in PRO version)

I really don't know ㅠㅠ haha

Have a nice day. Thank you always.

**Comment by qwtel** [comment]
You can do it like this: https://github.com/hydecorp/hydejack-site/blob/master/_showcase/shawn-yeager.md?plain=1#L21

**Comment by prettygood236** [comment]
Thank you. but it do not work like below code. 
```
accent_image: 
  background: /assets/img/background/44-green-yellow.jpg
  overlay: false
```
or 

```
accent_image: 
  url: /assets/img/background/44-green-yellow.jpg
  overlay: false
```
```
accent_image: 
  path: /assets/img/background/44-green-yellow.jpg
  overlay: false
```

How do I get overlay false while using an image as background?
