### ISSUE TITLE
dark mode and searchbox not working when built online

### ISSUE THREAD

**Issue by djccnt15** [hydecorp/hydejack#301]
strangly, dark mode and searchbox not working-more like it's not built- when built online.

First, I started to build blog with free version, and then upgraded to PRO version.

I'm pretty sure I applied pretty much everything from PRO version, and confirmed dark mod and searchbox is working when it is built on my local.

However, when I pushed it to github repo, it seems like dark mode and searchbox is not built.

I hope I could use your help here.

link of my repo: https://github.com/djccnt15/djccnt15.github.io
link of my blog: https://djccnt15.github.io/

Thank you always. Have a nice day!

**Comment by djccnt15** [comment]
sry it was my mistake of setting. I fixed by myself

**Comment by chenq9901-logic** [comment]
Hi @djccnt15! Thanks for your question and I meet the same problem now :( How did you solve that?

**Comment by djccnt15** [comment]
> Hi @djccnt15! Thanks for your question and I meet the same problem now :( How did you solve that?

sry. it's been quite long and I don't remember everything.

all I remember is it was fixed after I integrated PRO version properly

**Comment by chenq9901-logic** [comment]
> Hi

Thanks! Then I'll try to fix it by myself :)
