### ISSUE TITLE
Related Posts by category

### ISSUE THREAD

**Issue by iAmG-r00t** [hydecorp/hydejack#302]
Is there a way one can get related posts by category instead of writing the path with `related_posts:`

**Comment by qwtel** [comment]
That is the default behavior if `page.related_posts` is not defined and `site.hydejack.use_lsi` is false: [see here](https://github.com/hydecorp/hydejack/blob/a1d06e63eca202a320f952c84e70b2ce6b55366e/_includes/components/related-posts.html#L14)

**Comment by iAmG-r00t** [comment]
thank you, I hadn't set `use_lsi` as `false`
