### ISSUE TITLE
Add a “Back to Top” Button, it works locally, but can't appear correctly on github.io

### ISSUE THREAD

**Issue by junjie-yin** [hydecorp/hydejack#306]
# Page and repository
The above-mentioned page is [**https://junjie-yin.github.io/**](https://junjie-yin.github.io/), from this [**repository**](https://github.com/junjie-yin/junjie-yin.github.io/)
# Issue description

I add a “Back to Top” Button in the main file `index.html` (the last 50 lines), it works **locally**.
When the page scroll>20px (**The page has to be scrolled for it to show**); The "Back to Top" Button appear

![54e9833396f2794b2c2daaec91a65e5](https://user-images.githubusercontent.com/57343270/188085277-4197db08-a5bd-40ac-805b-d1b2816874b5.jpg)
<br>
 But the button can't appear, other elements show correctly on github.io (the workflows report no bug)

![6497dfc5fa8b2532cd30708559da6e8](https://user-images.githubusercontent.com/57343270/188084518-3803e91a-7e0e-4e26-a115-6340c3aee269.jpg)

# Menthods I have tried

1. add the code to <head></head>   <body></body> in the main file `index.html`, respectively.
2. add the code to `_layouts/page.yml`
3. add into global scripts `__includes/my-scripts.html`      following the instruction from [**hydejack.com**](https://hydejack.com/docs/scripts/#global-scripts)

But all of the tries failed.

# Minimum Work Example

[MWE-locally.zip](https://github.com/hydecorp/hydejack/files/9476249/MWE-locally.zip)  This file can be built locally in CMD     

```
bundle install
```

```
bundle exec jekyll serve
```

# "Back to Top" Code

```html

<!-- 
  ####################################################################
  BACK TO TOP
  ####################################################################
-->
<style>
  #myBtn {
    width:50px;
    height:50px;
    display: none;
    position: fixed;
    bottom: 20px;
    right: 30px;
    z-index: 99;
    border: none;
    outline: none;
    background-color: #555;
    color: white;
    cursor: pointer;
    padding: 5px 5px 5px 5px;
    border-radius: 50%;
    font-size:25px;
  }
  
  #myBtn:hover {
    background-color: rgb(0,87,156);
  }
</style>

<body>
<button onclick="topFunction()" id="myBtn" title="Back to Top"><span class="icon-arrow-up1"></span></button>

<script>
// When the page scroll>20px ; The "Back to Top" Button appear
window.onscroll = function() {scrollFunction()};

function scrollFunction() {console.log(121);
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
      document.getElementById("myBtn").style.display = "block";
  } else {
      document.getElementById("myBtn").style.display = "none";
  }
}

// Click the button, then it will back to top
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}
</script>
</body>



```

**Comment by inseonyun** [comment]
Oh, you've implemented that feature yourself. so cool, In my case I used someone else's open source like this
+ _includes/components/dingbat.html

![image](https://user-images.githubusercontent.com/84364741/188303134-9e40ffe0-3058-4b5f-bf84-7de381562a1f.png)

**Comment by junjie-yin** [comment]
Thanks, dude! Your method works. And I send an email for you,
